Feature 31 distribution screen
Metatavu/seligson-taskusalkku pull request #34
Opened 2022-01-13 09:08 UTC by Chi-Chu319

resolves #31

2022-01-14 14:01 UTC, jarinykanen requested changes

2022-01-14 14:01 UTC, jarinykanen commented on src/components/screens/portfolio/distributions-screen.tsx
> +  React.useEffect(() => {
Add docs and change to single line

2022-01-14 14:01 UTC, jarinykanen commented on src/components/screens/portfolio/distributions-screen.tsx
> +  };
```suggestion
  const renderCategories = () => (
    <Card style={ styles.distributionCard }>
      { portfolioSecurityCategories.map(renderCategory) }
    </Card>
  );
```

2022-01-16 14:02 UTC, anttileppa requested changes

2022-01-16 14:02 UTC, anttileppa commented on src/components/screens/portfolio/distributions-screen.tsx
> +  const renderPie = () => {
Securities should be sortted by their percentage

2022-01-17 10:32 UTC, jarinykanen approved these changes

2022-01-17 10:32 UTC, merged